# Generated by Django 4.1.7 on 2023-03-22 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('workload_min', models.IntegerField()),
                ('workload_max', models.IntegerField()),
                ('use', models.IntegerField()),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modality.modality')),
            ],
        ),
    ]
