# Generated by Django 4.1.7 on 2023-03-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=8, verbose_name='Matrícula')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
        ),
    ]
